org.gradle.jvmargs=-Xmx3G
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

minecraftVersion=26.1.2
modVersion=26.1.2-1.0.1
currentChangelog=- Added Essentia (thaumaturge) support

refinedarchitectVersion=1.7.1
refinedstorageVersion=3.2.1
arsNouveauVersion=
industrialForegoingVersion=
titaniumVersion=
thaumaturgeVersion=9091148
lithostitchedVersion=8944658
curiosVersion=8463519
refinedstorageJeiIntegrationVersion=2.0.1
refinedstorageEmiIntegrationVersion=

jeiVersion=29.5.0.24
emiVersion=
