org.gradle.jvmargs=-Xmx3G
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

minecraftVersion=26.1.2
modVersion=26.1.2-1.0.0
currentChangelog=- 26.1.2 port\n- Removed Ars Nouveau, Industrial Foregoing Souls support as they aren't ported yet

refinedarchitectVersion=1.6.4
refinedstorageVersion=3.2.1
arsNouveauVersion=
industrialForegoingVersion=
titaniumVersion=
refinedstorageJeiIntegrationVersion=2.0.1
refinedstorageEmiIntegrationVersion=

jeiVersion=29.5.0.24
emiVersion=
