@ParametersAreNonnullByDefault
@FieldsAndMethodsAreNonnullByDefault
package com.ultramega.refinedtypes.datagen.advancement;

import com.refinedmods.refinedstorage.api.core.FieldsAndMethodsAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
